## 基本操作

In [1]:
import numpy as np
import pandas as pd

矩阵运算


        - 普通乘积运算符 **
        - 矩阵乘积运算符* ，按元素进行运算
        - 矩阵乘积运算符 @ 或者 dot，按矩阵运算
        - += 和 *= 在原数组上修改 （数组大小不可原地修改）
        - 不同类型的数组也可以运算，类型会自动“向上转换”

In [2]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [7]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

In [8]:
A*B

array([[2, 0],
       [0, 4]])

In [9]:
A @ B

array([[5, 4],
       [3, 4]])

In [11]:
A.dot(B)

array([[5, 4],
       [3, 4]])

        - ndarray类的常用运算方法

In [13]:
a=np.random.random((2,3))
a

array([[0.90666457, 0.33351902, 0.79808311],
       [0.43835924, 0.87192554, 0.46048824]])

In [14]:
a.sum()

3.8090397153174296

In [15]:
a.min()

0.33351902312672765

In [16]:
a.max()

0.9066645654214773

        - 指定axis，沿着某一轴操作

In [17]:
b=np.arange(12).reshape(3,4)
b.sum(axis=0)

array([12, 15, 18, 21])

        - cumsum()：累加求和

In [18]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

数学函数

        - np.sin(A)
        - np.cos(A)
        - np.exp(A)
        - np.sqrt(A)
        - np.add(A,B)

In [19]:
B=np.arange(3)
B

array([0, 1, 2])

In [20]:
np.sin(B)

array([0.        , 0.84147098, 0.90929743])

In [21]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [22]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])