## 索引、切片和迭代

https://www.numpy.org.cn/user/quickstart.html#%E7%B4%A2%E5%BC%95%E3%80%81%E5%88%87%E7%89%87%E5%92%8C%E8%BF%AD%E4%BB%A3

In [1]:
import numpy as np
import pandas as pd

### 一维数组

In [13]:
a=np.arange(10)**3
#3次方
print("a=",a)

print(a[2])
print(a[2:5])
#间隔赋值
a[:6:2]=-1000
print(a)
# 翻转
print(a[::-1])

a= [  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [15]:
#迭代
for i in a:
    print(i**(1/3.))#三次方根

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/tmp/ipykernel_344/2294513898.py:3: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))#三次方根


### 多维数组

    - 切片

In [32]:
def f(x,y):
    return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)
print(b)

print(b[0,2])

#第1列的0-4行数
print(b[0:5,1])
#第1列的所有数
print(b[:,1])
#第1-2行的所有数
print(b[1:3,:])

#缺失的索引默认为 [:]
print(b[-1])
#等价于b[-1,:]最后一行的所有数


#...表示省略余下的所有轴:::
#若共有5个轴
# x[1,2,...]等价于x[1,2,:,:,:]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
2
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


    - 迭代

In [34]:
#默认对于第一个轴迭代
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [35]:
#对array.flat属性迭代，表示对多维数组中每个元素迭代
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### 数组重构

In [48]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.shape)

[[2. 7. 9. 4.]
 [5. 5. 7. 2.]
 [2. 8. 0. 0.]]
(3, 4)


    重构为新数组，不改原始数组

In [49]:
#拉平成一维数组
a.ravel()

a.reshape(6,2)

#转置
a.T

array([[2., 5., 2.],
       [7., 5., 8.],
       [9., 7., 0.],
       [4., 2., 0.]])

    ndarray.resize会修改原始数组

In [51]:
print(a)

a.resize((2,6))
print(a)

#reshape参数为-1，表示自动计算
print(a.reshape(3,-1))


[[2. 7. 9. 4. 5. 5.]
 [7. 2. 2. 8. 0. 0.]]
[[2. 7. 9. 4. 5. 5.]
 [7. 2. 2. 8. 0. 0.]]
[[2. 7. 9. 4.]
 [5. 5. 7. 2.]
 [2. 8. 0. 0.]]


    数组堆叠

In [52]:
a=np.floor(10*np.random.random((2,2)))
print(a)
b=np.floor(10*np.random.random((2,2)))
print(b)

[[6. 3.]
 [3. 3.]]
[[3. 1.]
 [0. 9.]]


In [53]:
#垂直堆叠
np.vstack((a,b))

array([[6., 3.],
       [3., 3.],
       [3., 1.],
       [0., 9.]])

In [54]:
#水平堆叠
np.hstack((a,b))

array([[6., 3., 3., 1.],
       [3., 3., 0., 9.]])

In [63]:
from numpy import newaxis

#将数个一维数组作为列，堆成二维数组
a=np.array([4.,2.])
b=np.array([3.,8.])
print(np.column_stack((a,b)))

#区别
print(np.hstack((a,b)))


[[4. 3.]
 [2. 8.]]
[4. 2. 3. 8.]


In [64]:
#区别在于，column_stack多了扩维的步骤，如下
print( a[:,newaxis] )
print( b[:,newaxis] )

[[4.]
 [2.]]
[[3.]
 [8.]]


In [66]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [68]:
#等价
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

    - 数组拆分

In [72]:
a=np.floor(10*np.random.random((2,12)))
print(a)

#垂直分割为3块
print( np.hsplit(a,3) )

#垂直分割，指定分割点在：第3列之后，和，第4列之后
print( np.hsplit(a,(3,4)) )

[[8. 3. 5. 0. 9. 4. 6. 7. 9. 6. 9. 1.]
 [3. 2. 6. 3. 2. 7. 8. 4. 5. 8. 1. 8.]]
[array([[8., 3., 5., 0.],
       [3., 2., 6., 3.]]), array([[9., 4., 6., 7.],
       [2., 7., 8., 4.]]), array([[9., 6., 9., 1.],
       [5., 8., 1., 8.]])]
[array([[8., 3., 5.],
       [3., 2., 6.]]), array([[0.],
       [3.]]), array([[9., 4., 6., 7., 9., 6., 9., 1.],
       [2., 7., 8., 4., 5., 8., 1., 8.]])]
