## 创建数组

        - ndarray和python array的区别：ndarray扩容需新建
        - ndarray特点：矢量化+广播

In [1]:
import numpy as np

普通数组

In [2]:
np.array([2,3,4])

array([2, 3, 4])

特殊数组

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.empty((4,4))

array([[0.00000000e+000, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

范围数组

In [11]:
np.arange(3) #个数

array([0, 1, 2])

In [12]:
np.arange(0,10,2) #步长

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0,10,2) #个数

array([ 0., 10.])